export default {
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  LOADING: 'LOADING',
  CLEAR_ERROR: 'CLEAR_ERRORS',

  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

  SET_CURRENT_USER_PROFILE: 'SET_CURRENT_USER_PROFILE'
};
