export default {
  GET_ARTICLES: 'GET_ARTICLES',
  GET_EXPLORE_ARTICLES: 'GET_EXPLORE_ARTICLES',
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  ARTICLE_FORM_SUCCESS: 'ARTICLE_FORM_SUCCESS',
  ARTICLES_ERROS: 'ARTICLES_ERRORS',
  GET_USER_ARTICLES: 'GET_USER_ARTICLES',
  ARTICLES_LOADING: 'ARTICLES_LOADING'
};
